openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/articles/:
    get:
      operationId: ArticleList
      description: List articles, optionally filtered by title string
      parameters:
      - in: header
        name: X-Request-ID
        schema:
          type: string
        description: Optional correlation id for tracing.
      - in: query
        name: q
        schema:
          type: string
        description: Case-insensitive title search.
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
          description: ''
    post:
      operationId: ArticleCreate
      description: 'Create a new article. Authentication required. '
      parameters:
      - in: header
        name: X-Request-ID
        schema:
          type: string
        description: Optional correlation id for tracing.
      tags:
      - articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ArticleCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ArticleCreate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleCreate'
          description: ''
        '400':
          description: Bad request
  /api/articles/{id}/:
    get:
      operationId: ArticleRetrieve
      description: Retrieve a single article by slug
      parameters:
      - in: header
        name: X-Request-ID
        schema:
          type: string
        description: Optional correlation id for tracing.
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this article.
        required: true
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
        '404':
          description: Not found
    put:
      operationId: api_articles_update
      description: |-
        Why a ViewSet?
        - One class encapsulates all CRUD operations.
        - Router auto-generates clean URLs.
        - drf-spectacular can document each action with @extend_schema
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this article.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArticleUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ArticleUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ArticleUpdate'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleUpdate'
          description: ''
    patch:
      operationId: ArticlePartialUpdate
      description: Partially update an article you own.
      parameters:
      - in: header
        name: X-Request-ID
        schema:
          type: string
        description: Optional correlation id for tracing.
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this article.
        required: true
      tags:
      - articles
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedArticleUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedArticleUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedArticleUpdate'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
          description: ''
        '400':
          description: Bad request
        '403':
          description: Forbidden
    delete:
      operationId: ArticleDelete
      description: Delete an article you own
      parameters:
      - in: header
        name: X-Request-ID
        schema:
          type: string
        description: Optional correlation id for tracing.
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this article.
        required: true
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: Deleted
        '403':
          description: Forbidden
  /api/schema/:
    get:
      operationId: api_schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Article:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        body:
          type: string
        owner:
          type: string
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        updated:
          type: string
          format: date-time
          readOnly: true
      required:
      - body
      - created
      - owner
      - slug
      - title
      - updated
    ArticleCreate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        body:
          type: string
      required:
      - body
      - title
    ArticleUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        body:
          type: string
      required:
      - body
      - title
    PatchedArticleUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        body:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
